name: Build & Test iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mostrar diretório atual e conteúdo
        run: |
          echo "Diretório atual:"
          pwd
          echo "Conteúdo do diretório atual:"
          ls -la
          echo "Buscando .xcodeproj..."
          find . -name "*.xcodeproj"

      - name: Mostrar estrutura de pastas
        run: |
          brew install tree || echo "tree já instalado"
          tree -a -L 3

      - name: Mostrar versão do Xcode
        run: xcodebuild -version

      - name: Mostrar versão do Swift
        run: swift --version

      - name: Definir versão do Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build do projeto
        run: |
          xcodebuild \
            -project Movies.xcodeproj \
            -scheme Movies \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            clean build

      - name: Executar testes
        run: |
          xcodebuild \
            -project Movies.xcodeproj \
            -scheme Movies \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            test
        continue-on-error: true
